name       : mixxx
version    : 2.2.3
release    : 15
source     :
    - https://github.com/mixxxdj/mixxx/archive/release-2.2.3.tar.gz : 69230dca511ba08a284a22a979ff05b62130e97156d39a044bb4045f5f43cd2e
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Mixxx is Free DJ software that gives you everything you need to perform live mixes.
description: |
    Mixxx is Free DJ software that gives you everything you need to perform live mixes.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(flac)
    - pkgconfig(glu)
    - pkgconfig(libavcodec)
    - pkgconfig(libchromaprint)
    - pkgconfig(libmodplug)
    - pkgconfig(libusb-1.0)
    - pkgconfig(lilv-0)
    - pkgconfig(opusfile)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(rubberband)
    - pkgconfig(shout)
    - pkgconfig(sndfile)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(upower-glib)
    - pkgconfig(vamp-hostsdk)
    - pkgconfig(vorbisfile)
    - pkgconfig(wavpack)
    - pkgconfig(x11)
    - pkgconfig(x264)
    - id3lib-devel
    - libid3tag-devel
    - libmad-devel
    - portmidi-devel
    - scons
    - vamp-plugin-sdk
build      : |
    scons %JOBS% \
        prefix=/usr \
        build=release \
        optimize=portable \
        qt_sqlite_plugin=0 \
        localecompare=1 \
        virtualize=0 \
        modplug=1 \
        ffmpeg=1 \
        opus=1 \
        wv=1
install    : |
    scons prefix=/usr install_root="$installdir/usr" install
    install -Dm00644 res/linux/mixxx.usb.rules $installdir/usr/lib64/udev/rules.d/100-mixxx.usb.rules
