name       : mixxx
version    : 2.3.3
release    : 28
source     :
    - https://github.com/mixxxdj/mixxx/archive/refs/tags/2.3.3.tar.gz : 8e3a5a545175982336bb07c81a3839897a007c43689b93641242db662f6beb9c
homepage   : https://mixxx.org/
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Mixxx is Free DJ software that gives you everything you need to perform live mixes
description: |
    Mixxx is Free DJ software that gives you everything you need to perform live mixes.
networking : yes   # libkeyfinder submodule
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(flac)
    - pkgconfig(glu)
    - pkgconfig(id3tag)
    - pkgconfig(libavcodec)
    - pkgconfig(libchromaprint)
    - pkgconfig(libmodplug)
    - pkgconfig(libusb-1.0)
    - pkgconfig(lilv-0)
    - pkgconfig(mad)
    - pkgconfig(opusfile)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(protobuf)
    - pkgconfig(rubberband)
    - pkgconfig(shout)
    - pkgconfig(sndfile)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(upower-glib)
    - pkgconfig(vamp-hostsdk)
    - pkgconfig(vorbisfile)
    - pkgconfig(wavpack)
    - pkgconfig(x11)
    - pkgconfig(x264)
    - id3lib-devel
    - lame-devel
    - portmidi-devel
    - qtkeychain-devel
    - vamp-plugin-sdk
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 res/linux/mixxx-usb-uaccess.rules $installdir/usr/lib64/udev/rules.d/100-mixxx-usb-uaccess.rules
