name       : mixxx
version    : 2.1.0
release    : 8
source     :
    - https://github.com/mixxxdj/mixxx/archive/release-2.1.0.tar.gz : 148b0ab222fa1c310e62b566d87c0a3d43fdee9435150d40d62055dbc228d396
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Mixxx is Free DJ software that gives you everything you need to perform live mixes.
description: |
    Mixxx is Free DJ software that gives you everything you need to perform live mixes.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(flac)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libavcodec)
    - pkgconfig(libchromaprint)
    - pkgconfig(libusb-1.0)
    - pkgconfig(ogg)
    - pkgconfig(opus)
    - pkgconfig(opusfile)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(protobuf)
    - pkgconfig(QtCore)
    - pkgconfig(rubberband)
    - pkgconfig(shout)
    - pkgconfig(sndfile)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(upower-glib)
    - pkgconfig(vamp-hostsdk)
    - pkgconfig(vorbisfile)
    - pkgconfig(x11)
    - pkgconfig(x264)
    - faad-devel
    - id3lib-devel
    - libid3tag-devel
    - libmad-devel
    - portmidi
    - scons
build      : |
    scons %JOBS% \
        prefix=/usr \
        optimize=native \
        build=release \
        qt_sqlite_plugin=0 \
        localecompare=1 \
        opus=1 \
        virtualize=0
install    : |
    scons prefix=/usr install_root="$installdir/usr" install
