name       : mixxx
version    : 2.2.0
release    : 12
source     :
    - https://github.com/mixxxdj/mixxx/archive/release-2.2.0.tar.gz : 03c819a55b1abee778c02d2ad889246c9ead9dd2948572a711b2aa94e4839faf
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Mixxx is Free DJ software that gives you everything you need to perform live mixes.
description: |
    Mixxx is Free DJ software that gives you everything you need to perform live mixes.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(flac)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libavcodec)
    - pkgconfig(libchromaprint)
    - pkgconfig(libusb-1.0)
    - pkgconfig(lilv-0)
    - pkgconfig(ogg)
    - pkgconfig(opus)
    - pkgconfig(opusfile)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(rubberband)
    - pkgconfig(shout)
    - pkgconfig(sndfile)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(upower-glib)
    - pkgconfig(vamp-hostsdk)
    - pkgconfig(vorbisfile)
    - pkgconfig(x11)
    - pkgconfig(x264)
    - faad-devel
    - id3lib-devel
    - libid3tag-devel
    - libmad-devel
    - portmidi-devel
    - scons
build      : |
    scons %JOBS% \
        prefix=/usr \
        optimize=portable \
        build=release \
        qt_sqlite_plugin=0 \
        localecompare=1 \
        opus=1 \
        virtualize=0
install    : |
    scons prefix=/usr install_root="$installdir/usr" install
    install -Dm00644 res/linux/mixxx.usb.rules $installdir/usr/lib64/udev/rules.d/100-mixxx.usb.rules
