name       : mixxx
version    : 2.0.0
release    : 6
source     :
    - http://downloads.mixxx.org/mixxx-2.0.0/mixxx-2.0.0-src.tar.gz : e1b8f33bba35046608578095ed3209967034579252d84c99e6bc03ec030f676d
license    : GPL-2.0
component  : multimedia.audio
summary    : Mixxx is Free DJ software that gives you everything you need to perform
    live mixes.
description: |
    Mixxx is Free DJ software that gives you everything you need to perform live mixes.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(flac)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libavcodec)
    - pkgconfig(libchromaprint)
    - pkgconfig(libusb-1.0)
    - pkgconfig(ogg)
    - pkgconfig(opus)
    - pkgconfig(opusfile)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(protobuf)
    - pkgconfig(QtCore)
    - pkgconfig(rubberband)
    - pkgconfig(shout)
    - pkgconfig(sndfile)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(vamp)
    - pkgconfig(vorbisfile)
    - pkgconfig(x11)
    - pkgconfig(x264)
    - faad-devel
    - id3lib-devel
    - libid3tag-devel
    - libmad-devel
    - portmidi
    - scons
setup      : |
    %patch -p1 < $pkgfiles/gcc6.patch
    %patch -p1 < $pkgfiles/mixxx-2.0.0-chromaprint-1.4.0.patch
    %patch -p1 < $pkgfiles/0009-Include-sqlite3.h-instead-of-forward-declaring-typed.patch
build      : |
    scons prefix=/usr %JOBS% qt_sqlite_plugin=0 localecompare=1 optimize=portable opus=1 virtualize=0
install    : |
    scons prefix=/usr install_root="$installdir/usr" install
